### ISSUE TITLE
Error restarting Solr after create the collection to index hive table

### ISSUE THREAD

**Issue by theyaa** [lucidworks/hive-solr#18]
I followed your example to create the Solr table and collection, but now when I try to restart Solr server I get this error.

java.io.IOException: Path <path to collection>/conf does not exist
	at org.apache.solr.common.cloud.ZkConfigManager.uploadToZK(ZkConfigManager.java:56)
	at org.apache.solr.common.cloud.ZkConfigManager.uploadConfigDir(ZkConfigManager.java:120)
	at org.apache.solr.cloud.ZkController.bootstrapConf(ZkController.java:1762)
	at org.apache.solr.cloud.ZkCLI.main(ZkCLI.java:194)

Seems like creating the collection+ table does not create the conf folder automatically.

**Comment by ctargett** [comment]
Can you share details of how you created the collection in Solr? Was it created before the Hive table was created?

**Comment by theyaa** [comment]
Yes, I followed your example here and after creating the Solr table, I went and created the Solr collection. Then inserted some data there. But now when I restart Solr, it looks for the conf folder under the collection.

I used command: solr -c create <collection_name>

**Comment by ctargett** [comment]
I'm not sure what's going on, to be honest. If you were able to insert some data to the collection in Solr, we could assume the collection is fine, but the error you are seeing indicates that the collection was not created correctly.

You're using SolrCloud, correct? If so, can you check what you see in ZooKeeper for this collection? You can see this via the Admin UI. Click on "Cloud" in the left-nav, then "Tree", then /configs. You should see a folder under there with your collection name.

**Comment by theyaa** [comment]
Thank you for the quick replies, I think the issue was with the collection sync with the external table. I deleted everything and restarted fresh and it seems to be working fine.
