### ISSUE TITLE
Make the id field not required in the Solr external table since I have Solr auto generate it

### ISSUE THREAD

**Issue by theyaa** [lucidworks/hive-solr#20]
I would like the Id to be auto generated by Solr everytime I insert a document into the collection. I created the collection to do so but the Solr external table is not allowing me to insert data without  providing the id field.

Is there a way to create the Solr table without the id field and let Solr auto assign it to the documents?

Thanks

**Comment by shazack** [comment]
Check out: UUID Section in 
https://wiki.apache.org/solr/UniqueKey#Unique_key_composition

**Comment by ctargett** [comment]
This was fixed with #27, which would be the 3.0.0 version of the SerDe.
