### ISSUE TITLE
Multivalued solr field support 

### ISSUE THREAD

**Issue by lilila** [lucidworks/hive-solr#3]
Could you please show an example to create a hive table from an existing Solr index. 
Thanks

**Comment by lilila** [comment]
Sorry the example given in the README works as long as I try to map single value fields. 
Is there a way to map a solr multivalue string field (*_ss ) into an array of string in hive?

**Comment by acesar** [comment]
It does not support Solr multivalue yet:

[source](https://github.com/lucidworks/hive-solr/blob/master/solr-hive-core/src/main/java/com/lucidworks/hadoop/hive/LWSerDe.java#L76)

It is only adding the first value.

Can you change the title of the issue? "MultiValue support"?

**Comment by lilila** [comment]
Thanks for the reply. By chance,  are you planning to add multivalued field support ?

**Comment by acesar** [comment]
yes, It will be scheduled.

**Comment by vttu** [comment]
Any update on this? I'm trying to get a hive array into solr.

**Comment by acesar** [comment]
fix in https://github.com/lucidworks/hive-solr/pull/27
