### ISSUE TITLE
Something problems about running on hive2.2

### ISSUE THREAD

**Issue by jhkkhtd** [lucidworks/hive-solr#30]
I tested hive-solr on hive1.2.1 ,it is fine. But when testing in hive2.2 ,it shows that 
 " java.lang.NoClassDefFoundError: com/lucidworks/hadoop/hive/LWSerDe " 

How can i solve these problems? please.

**Comment by ctargett** [comment]
Hive 2 is not expected to be supported until sometime this Summer.
