### ISSUE TITLE
Not Able to build

### ISSUE THREAD

**Issue by pike007** [lucidworks/hive-solr#6]
I am not to build this project as per instruction in readme, getting following exceptions:

C:\work\solr\hive-solr-master\solr-hive-core\src\main\java\com\lucidworks\hadoop\hive\LWHiveInputFormat.java:3: ****error: package com.lucidworks.hadoop.io does not exist****
import com.lucidworks.hadoop.io.LWMapRedInputFormat;
                               ^

How to resolve  "com.lucidworks.hadoop.io does not exist**** ", Please help here

I am new with gradle

**Comment by pike007** [comment]
common content was not got downloaded while downloading zip, so manually downloaded and and worked

**Comment by ctargett** [comment]
That package comes from a submodule, which needs to be initialized before building the .jar. I see the README is a poorly formatted and doesn't make this clear, so I'll fix that up for future users.
